###
# Default configuration:
#     Stores default configuration object for application. Most values
#     will have to be overridden for development, testing, or production
#     environments. Objects that *must* be overridden will be captioned
#     with an @override tag.
###
server:
  port: 3010

api:
  base_server_url: "https://hlab.dev"
  base_api_url: "/jsonapi"

###
# Logging configuration for application. Only directory for logs
# configurable thus far.
###
logging:
  directory: "./logs"